# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2bfc35dc1b48a89b7450533c14e950f61aedd361233feb32c001aa399512c9088b32791c49f516581a8516e887541afa73be6b3cb926187bf8f79dd9e140f70

test:
  secret_key_base: a11b5af8ebd0ee1973d887869ffa82991695da974ec541cd51e180dabde73d40802f324c01a814598d97871297ca062c99487c882061de2630eb1ea03751d4a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
